version: '3.8'

services:
  oracledb:
    image: nguyenphiikhanh/oracle-19c:ee
    container_name: oracle-db-19c-ee
    ports:
      - "${ORA_HOST_PORT}:1521"
      - "${ORA_OEM_PORT}:5500"
    environment:
      - ORA_PDB=${ORA_PDB}
      - ORACLE_PWD=${ORA_PWD}
    volumes:
      - ./oradata/:/opt/oracle/oradata/
