version: '3.8'

services:
  oraclelinux_ssh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: ${SSH_USERNAME}
        SSH_PASSWORD: ${SSH_PASSWORD}
    container_name: oracle-linux
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ./server/ssh:/etc/ssh
      - ./server/home:/home
      - ./server/log:/var/log
      - ./server/dnf:/var/cache/dnf
    restart: unless-stopped